# Generated by Django 5.1.4 on 2024-12-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='courses/thumbnails/')),
                ('access', models.CharField(choices=[('anyone', 'Anyone'), ('email', 'Email Required')], default='anyone', max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('coming_soon', 'Coming Soon'), ('published', 'Published')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
