# Generated by Django 5.1.4 on 2024-12-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('anyone', 'Anyone'), ('email', 'Email Required')], default='email', max_length=35),
        ),
    ]
