# Generated by Django 5.1.4 on 2024-12-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', '-updated']},
        ),
    ]
