# Generated by Django 5.1.4 on 2024-12-12 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_lesson_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='lesson',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
