# Generated by Django 5.1.4 on 2024-12-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_created_at_course_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='public_id',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
